image:
  file: .gitpod.Dockerfile

tasks:
  - name: Download resources
    init: bash scripts/download_all_resources.sh

  - name: Launch environment
    command: |
      echo "Training environment is ready."
      echo "You can now explore the training notebooks or start running commands in the terminal."
      bash

