image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and activate clair3
    command: |
      source /opt/conda/etc/profile.d/conda.sh
      conda config --add channels defaults
      conda config --add channels bioconda
      conda config --add channels conda-forge
      conda create -n clair3 -c bioconda clair3 python=3.9.0 -y
      conda activate clair3
      echo "Training environment is ready."
      bash
