image:
  file: .gitpod.Dockerfile

tasks:
  - name: Launch environment
    command: |
      echo "Training environment is ready."
      echo "Explore training notebooks or run commands in the terminal."
      bash

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
